# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Registration of requests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Registration of requests
  pod ‘SQLite.swift’, :git => ‘https://github.com/stephencelis/SQLite.swift.git’, :branch => ‘master’

  target 'Registration of requestsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Registration of requestsUITests' do
    # Pods for testing
  end

end

